on:
  push:
    paths:
      - 'config/corne.keymap'
      - 'config/corne.conf'
      - 'build.yaml'
      - '.github/workflows/build-zmk.yml'
  pull_request:
    paths:
      - 'config/corne.keymap'
      - 'config/corne.conf'
      - 'build.yaml'
      - '.github/workflows/build-zmk.yml'
  workflow_dispatch:

jobs:
  zmk:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main