on:
  push:
    paths:
      - 'keyboards/keebio/iris_lm/k1/keymaps/graphite/keymap.json'
      - 'qmk.json'
      - '.github/workflows/build-qmk.yml'
  pull_request:
    paths:
      - 'keyboards/keebio/iris_lm/k1/keymaps/graphite/keymap.json'
      - 'qmk.json'
      - '.github/workflows/build-qmk.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  qmk:
    if: ${{ !vars.ACT || vars.RUN == 'qmk' }}
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
