name: build-zmk
on:
  push:
    paths:
      - 'config/graphite.dtsi'
      - 'config/corne.keymap'
      - 'config/corne.conf'
      - 'config/corne_left.conf'
      - 'config/eyelash_corne.keymap'
      - 'config/eyelash_corne.conf'
      - 'config/eyelash_corne_left.conf'
      - 'boards/eyelashperipherals/**'
      - 'config/totem.keymap'
      - 'config/totem.conf'
      - 'config/boards/shields/totem/**'
      - 'build.yaml'
      - '.github/workflows/build-zmk.yml'
  workflow_dispatch:

jobs:
  zmk:
    if: ${{ !vars.ACT || vars.RUN == 'zmk' }}
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
