name: build-zmk
on:
  push:
    paths:
      - 'config/graphite.dtsi'
      - 'config/corne.keymap'
      - 'config/corne.conf'
      - 'build.yaml'
      - '.github/workflows/build-zmk.yml'
  pull_request:
    paths:
      - 'config/corne.keymap'
      - 'config/corne.conf'
      - 'build.yaml'
      - '.github/workflows/build-zmk.yml'
  workflow_dispatch:

jobs:
  zmk:
    if: ${{ !vars.ACT || vars.RUN == 'zmk' }}
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
